routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});
//Route::resource('/', 'BunchController');

Auth::routes();
Route::get('/', 'PostController@index');
Route::resource('/posts', 'PostController');
Route::resource('/comment', 'CommentController');
Route::post('/comment-update', 'CommentController@update');

Route::post('/comment-delete', 'CommentController@destroy');
Route::resource('/users', 'UserController');
Route::post('/users-update', 'UserController@update');
Route::post('/users-delete', 'UserController@destroy');

//Route::get('/', 'PostController@index');
//Route::get('/post/create', 'PostController@create');
//Route::post('/store', 'PostController@store');
//Route::get('/show{id}', 'PostController@show');
//Route::get('/home', 'HomeController@index')->name('home');
//Route::post('/store', 'PostController@store');
//Route::post('/', ['as' => 'form-group', 'uses' => 'PostController@store']);
//Route::post('/', ['as' => 'form_url', 'uses' => 'PostController@store']);

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Concerns\HasTimestamps;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
class Post extends Model
{
    use HasTimestamps;
    protected $fillable = ['id', 'title', 'text', 'created_by', 'updated_by' ];
//    protected $appends = array('photos');
    protected $appends = ['photos', 'author'];

    public function getPhotosAttribute()
    {
        $post_id = $this->id;

            return $this->photos = DB::table('galleries')->where(['post_id' => $post_id])->value('photo');
    }
    public function getAuthorAttribute()
    {
        return $this->author = DB::table('users')->where(['id' => $this->created_by])->value('name');
    }
    public static function boot()
    {
        parent::boot();

        static::updating(function ($table) {
            $table->updated_by = Auth::user()->id;
        });
        static::creating(function ($table) {
            $table->created_by = Auth::user()->id;
            $table->updated_by = Auth::user()->id;
        });


    }

    public function post(){
        return $this->hasMany(Gallery::class);
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use App\Post;
use Illuminate\Http\Request;
use App\Http\Requests\PostRequest;
use Illuminate\Support\Facades\Storage;
use App\Gallery;
use Illuminate\Support\Facades\DB;
class PostController extends Controller
{
    protected $comment;
    public function __construct(Comment $comment)
    {
        $this->comment = $comment;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Post $post)
    {
        $posts = $post->orderBy('created_at', 'DESC')->get();
        return view('post.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('post.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Post $post, PostRequest $request)
    {
        $id = $post->create($request->all())->id;
        if($files=$request->file('photos')){
            $i=0;
            foreach($files as $file){
                $photoName = time().$i++.'.'.$file->getClientOriginalExtension();
                $file->move(public_path('post_photo'), $photoName);
                $photos[]=$photoName;
                DB::table('galleries')->insert(['post_id' => $id, 'photo' => $photoName]);
            }
        }

        return redirect()->route('posts.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        $photos = DB::table('galleries')->where(['post_id' => $post->id])->get();
        $comments = $this->comment->where([
            ['post_id', '=', $post->id],
            ['reference_id', '=', '0'],
        ])->get();
        $ref_comments = $this->comment->where([
            ['post_id', '=', $post->id],
            ['reference_id', '>', '0'],
        ])->get();
        return view('post.show', compact('post'),  compact('photos'))->with(compact('comments'))->with(compact('ref_comments'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {$this->authorize('update',$post);
        return view('post.edit' , compact('post') );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Post $post, PostRequest $request)
    {$this->authorize('update',$post);
            if($files=$request->file('photos')){
                DB::table('galleries')->where('post_id', $post->id)->delete();
                $i=0;
                foreach($files as $file){
                    $photoName = time().$i++.'.'.$file->getClientOriginalExtension();
                    $file->move(public_path('post_photo'), $photoName);
                    $photos[]=$photoName;
                    DB::table('galleries')->insert(['post_id' => $post->id, 'photo' => $photoName]);
                }
            }
        $post->update($request->all());

        return redirect()->route('posts.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {$this->authorize('delete',$post);
        $post->delete();
        return redirect()->route('posts.index');
    }
}

resources/views/post/_form.blade.php
<div class="form-group ">
    <label for="title">Title:</label>
    <input type="text" class="form-control" name="title" placeholder="Enter title" value="{{$post->title or NULL}}">
</div>
<div class="form-group ">
    <label for="text">Text:</label>
    <input type="text" class="form-control" name="text" placeholder="Text" value="{{$post->text or NULL}}">
</div>
<div class="form-group ">
    {{--<input type="file" name="photo">--}}
    Вы можете выбрать сразу несколько фотографий, для этого выделите их в окне выбора.
    <input type="file" class="form-control" name="photos[]" placeholder="address" multiple>

</div>

resources/views/post/create.blade.php
@extends('layouts.panel')
@section('panel')
    <div class="panel-heading container-fluid">
        {{--<div class="form-group">--}}
            {{--<div class="centered-child col-md-11 col-sm-10 col-xs-10"><b>New Post</b></div>--}}
        {{--</div>--}}
    </div>

    <div class="panel-body">

    <form method="post" action="{{action('PostController@store')}}" enctype="multipart/form-data">
        @csrf
        @include('post._form')
            <div class="form-group">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
    </form>
    </div>

@endsection

resources/views/post/edit.blade.php
@extends('layouts.panel')
@section('panel')
    <div class="panel-heading container-fluid">
        {{--<div class="form-group">--}}
        {{--<div class="centered-child col-md-11 col-sm-10 col-xs-10"><b>New Post</b></div>--}}
        {{--</div>--}}
    </div>

    <div class="panel-body">
        <form method="post" action="{{action('PostController@update', $post->id)}}" enctype="multipart/form-data">
            @csrf
            <input name="_method" type="hidden" value="PATCH">
            @include('post._form')
            <div class="form-group">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </form>
    </div>


@endsection

resources/views/post/index.blade.php
@extends('layouts.panel')
@section('panel')
    <div class="panel-heading container-fluid">
            <div class="container">

                <div class="row">
                    <div class="col-md-12">
                        @if (Auth::user() and Auth::user()->role_id == 2)
                            <a class = 'btn btn-outline-dark btn-xs btn-block' href={{ route('users.index')}}>Show Users List</a>
                        @endif
                        @if (Auth::user() and (Auth::user()->role_id == 2 or Auth::user()->role_id == 1))
                        <a class = 'btn btn-info btn-xs btn-block' href={{ route('posts.create')}}>Create NEW POST</a>
                        @endif

                    @foreach ($posts as $post)
                        <div class="card mb-4">
                            @if ($post->photos != NULL)
                            <img class="img-fluid rounded" src="{{asset('/post_photo/'.$post->photos)}}" alt="Card image cap">
                            @endif
                            <div class="card-body">
                                <h2 class="card-title">{{$post->title}}</h2>
                                <p class="card-text">{{ str_limit($post->text, $limit = 25, $end = '...') }}</p>
                                {{--<a class = 'btn btn-danger btn-xs' href={{ route('posts.destroy', ['id' => $post->id])}}>delete</a>--}}
                                @if (Auth::user() and ($post->created_by == Auth::user()->id or Auth::user()->role_id == 2))
                                <form action="{{ route('posts.destroy', ['id' => $post->id]) }}" method="POST" style="display: inline-block; float: right">
                                    {{ method_field('DELETE') }}
                                    {{ csrf_field() }}
                                    <button style="display: inline-block" class = 'btn btn-danger btn-xs'>Delete</button>
                                    <a class = 'btn btn-info btn-xs ' style="display: inline-block" href={{ route('posts.edit', ['id' => $post->id] )}}>Edit</a>
                                </form>
                                @endif
                                <a class="btn btn-primary btn" style="display: inline-block" href={{ route('posts.show', ['id' => $post->id])}} >Read More &rarr;</a>

                            </div>
                            <div class="card-footer text-muted">
                                {{$post->created_at}}
                            </div>
                        </div>
                        @endforeach
                    </div>
                </div>
            </div>
    </div>

@endsection

resources/views/post/show.blade.php
@extends('layouts.panel')
@section('panel')
    <div class="panel-heading container-fluid">
        @if (Auth::user() and ($post->created_by == Auth::user()->id or Auth::user()->role_id == 2))
            <form action="{{ route('posts.destroy', ['id' => $post->id]) }}" method="POST">
                {{ method_field('DELETE') }}
                {{ csrf_field() }}
                <button class = 'btn btn-danger btn-xs'>Delete</button>
                <a class = 'btn btn-info btn-xs ' href={{ route('posts.edit', ['id' => $post->id] )}}>Edit</a>
            </form>
        @endif
    </div>

    <div class="container">

        <div class="row">

            <div class="col-lg-10">

                <h1 class="mt-4">{{$post->title}}</h1>

                <p class="lead">
                    by
                    <a href="#">{{$post->author}}</a>
                </p>

                <hr>

                <p>{{$post->created_at}}</p>

                <hr>


                <hr>

                <p>{{$post->text}}</p>

                <hr>
                @if ($photos != NULL)
            @foreach ($photos as $photo)
                    <img class="img-fluid rounded" src="{{asset('/post_photo/'.$photo->photo)}}" alt="{{$photo->photo}}">
            @endforeach
            @endif
            @include('comment.create');
                @include('comment.index', ['comments' => $comments]);

            </div>

@endsection